# Generated by Django 4.0.2 on 2022-02-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires Date Time'),
        ),
    ]
